language: node_js
node_js:
  - v16
install:
  - npm install
jobs:
  include:
    - stage: Build
      env:
        global:
          - NODE_ENV=development
      script:
        - npm run lint
    - stage: npm release
      script: npm run lint
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_token: '$NPM_TOKEN'
        cleanup: false
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
